export const movies = [
  {
    id: 263501,
    movieId: 263501,
    t: '怒火·重案',
    year: '2021',
    r: 7.8,
    rc: 498,
    img: 'http://img5.mtime.cn/mt/2021/07/24/165813.84531124_1280X720X2.jpg',
    m: '',
    actors: '甄子丹 / 谢霆锋 / 秦岚 / 汤君慈',
    p: [
      '剧情',
      '动作'
    ],
    rd: null,
    d: '128分钟',
    rsC: 0,
    ua: 1,
    def: 0,
    commonSpecial: null,
    wantedCount: 288,
    movieType: '剧情 / 动作',
    versions: [
      {
        versionId: 1,
        version: '2D'
      }
    ],
    preferentialFlag: false,
    nearestShowtimeCount: 0,
    nearestCinemaCount: 0,
    nearestDay: 0,
    tCn: '怒火·重案',
    tEn: 'Raging Fire',
    dN: '陈木胜',
    aN1: '甄子丹',
    aN2: '谢霆锋',
    isHasTrailer: false,
    cC: 0,
    sC: 6600,
    isNew: false,
    isHot: true,
    isTicket: true,
    is3D: false,
    isIMAX: false,
    isIMAX3D: false,
    isDMAX: false,
    isPromotion: false
  },
  {
    id: 269352,
    movieId: 269352,
    t: '盛夏未来',
    year: '2021',
    r: 7.5,
    rc: 114,
    img: 'http://img5.mtime.cn/mt/2021/07/23/161851.14329984_1280X720X2.jpg',
    m: '',
    actors: '张子枫 / 吴磊 / 郝蕾 / 祖峰',
    p: [
      '剧情',
      '青春'
    ],
    rd: '20210730',
    d: '115分钟',
    rsC: 0,
    ua: 1,
    def: 0,
    commonSpecial: null,
    wantedCount: 192,
    movieType: '剧情 / 青春',
    versions: null,
    preferentialFlag: false,
    nearestShowtimeCount: 0,
    nearestCinemaCount: 0,
    nearestDay: 0,
    tCn: '盛夏未来',
    tEn: 'Upcoming Summer',
    dN: '陈正道',
    aN1: '张子枫',
    aN2: '吴磊',
    isHasTrailer: false,
    cC: 0,
    sC: 4347,
    isNew: false,
    isHot: true,
    isTicket: true,
    is3D: false,
    isIMAX: false,
    isIMAX3D: false,
    isDMAX: false,
    isPromotion: false
  },
  {
    id: 269746,
    movieId: 269746,
    t: '白蛇2：青蛇劫起',
    year: '2021',
    r: 7.4,
    rc: 496,
    img: 'http://img5.mtime.cn/mt/2021/07/07/142802.91625421_1280X720X2.jpg',
    m: '',
    actors: '唐小喜 / 张福正 / 魏超 / 赵铭洲',
    p: [
      '冒险',
      '奇幻',
      '动画'
    ],
    rd: '20210723',
    d: '131分钟',
    rsC: 0,
    ua: 1,
    def: 0,
    commonSpecial: null,
    wantedCount: 467,
    movieType: '冒险 / 奇幻 / 动画',
    versions: null,
    preferentialFlag: false,
    nearestShowtimeCount: 0,
    nearestCinemaCount: 0,
    nearestDay: 0,
    tCn: '白蛇2：青蛇劫起',
    tEn: '',
    dN: '黄家康',
    aN1: null,
    aN2: '赵霁',
    isHasTrailer: false,
    cC: 0,
    sC: 2630,
    isNew: false,
    isHot: true,
    isTicket: true,
    is3D: false,
    isIMAX: false,
    isIMAX3D: false,
    isDMAX: false,
    isPromotion: false
  },
  {
    id: 268874,
    movieId: 268874,
    t: '流浪猫鲍勃2：鲍勃的礼物',
    year: '2021',
    r: 0,
    rc: 26,
    img: 'http://img5.mtime.cn/mt/2021/07/30/100639.68367268_1280X720X2.jpg',
    m: '',
    actors: '卢克·崔德威 / 安娜·威尔逊-琼斯 / Kristina Tonteri-Young / Nina Wadia',
    p: [
      '家庭'
    ],
    rd: '20210806',
    d: '',
    rsC: 0,
    ua: 1,
    def: 0,
    commonSpecial: null,
    wantedCount: 42,
    movieType: '家庭',
    versions: null,
    preferentialFlag: false,
    nearestShowtimeCount: 0,
    nearestCinemaCount: 0,
    nearestDay: 0,
    tCn: '流浪猫鲍勃2：鲍勃的礼物',
    tEn: 'A Christmas Gift From Bob',
    dN: '查尔斯·马丁·史密斯',
    aN1: '卢克·崔德威',
    aN2: '安娜·威尔逊-琼斯',
    isHasTrailer: false,
    cC: 0,
    sC: 1894,
    isNew: true,
    isHot: false,
    isTicket: true,
    is3D: false,
    isIMAX: false,
    isIMAX3D: false,
    isDMAX: false,
    isPromotion: false
  },
  {
    id: 268794,
    movieId: 268794,
    t: '中国医生',
    year: '2021',
    r: 6.6,
    rc: 476,
    img: 'http://img5.mtime.cn/mt/2021/06/23/144247.59352538_1280X720X2.jpg',
    m: '',
    actors: '张涵予 / 袁泉 / 朱亚文 / 李晨',
    p: [
      '剧情'
    ],
    rd: '20210709',
    d: '129分钟',
    rsC: 0,
    ua: 1,
    def: 0,
    commonSpecial: null,
    wantedCount: 438,
    movieType: '剧情',
    versions: null,
    preferentialFlag: false,
    nearestShowtimeCount: 0,
    nearestCinemaCount: 0,
    nearestDay: 0,
    tCn: '中国医生',
    tEn: 'Chinese Doctors',
    dN: '刘伟强',
    aN1: '张涵予',
    aN2: '袁泉',
    isHasTrailer: false,
    cC: 0,
    sC: 1191,
    isNew: false,
    isHot: false,
    isTicket: true,
    is3D: false,
    isIMAX: false,
    isIMAX3D: false,
    isDMAX: false,
    isPromotion: false
  },
  {
    id: 270731,
    movieId: 270731,
    t: '我的爸爸是森林之王2',
    year: '2021',
    r: 0,
    rc: 2,
    img: 'http://img5.mtime.cn/mt/2021/07/29/165547.50792658_1280X720X2.jpg',
    m: '',
    actors: 'Jeremy Degruson / 本·斯塔森 / 卡尔·布伦克尔 / Bob Barlen',
    p: [
      '动画',
      '冒险',
      '喜剧'
    ],
    rd: '20210806',
    d: '89分钟',
    rsC: 0,
    ua: 1,
    def: 0,
    commonSpecial: null,
    wantedCount: 14,
    movieType: '动画 / 冒险 / 喜剧',
    versions: [
      {
        versionId: 1,
        version: '2D'
      },
      {
        versionId: 2,
        version: '3D'
      }
    ],
    preferentialFlag: false,
    nearestShowtimeCount: 0,
    nearestCinemaCount: 0,
    nearestDay: 0,
    tCn: '我的爸爸是森林之王2',
    tEn: '',
    dN: 'Jeremy Degruson,本·斯塔森',
    aN1: null,
    aN2: null,
    isHasTrailer: false,
    cC: 0,
    sC: 822,
    isNew: true,
    isHot: false,
    isTicket: true,
    is3D: true,
    isIMAX: false,
    isIMAX3D: false,
    isDMAX: false,
    isPromotion: false
  },
  {
    id: 269726,
    movieId: 269726,
    t: '我的父亲焦裕禄',
    year: '2021',
    r: 0,
    rc: 41,
    img: 'http://img5.mtime.cn/mt/2021/07/28/164812.49415441_1280X720X2.jpg',
    m: '',
    actors: '郭晓东 / 丁柳元 / 严晓频 / 蒋易',
    p: [
      '剧情',
      '传记'
    ],
    rd: '20210806',
    d: '108分钟',
    rsC: 0,
    ua: 1,
    def: 0,
    commonSpecial: null,
    wantedCount: 17,
    movieType: '剧情 / 传记',
    versions: null,
    preferentialFlag: false,
    nearestShowtimeCount: 0,
    nearestCinemaCount: 0,
    nearestDay: 0,
    tCn: '我的父亲焦裕禄',
    tEn: 'My Father',
    dN: '范元',
    aN1: null,
    aN2: null,
    isHasTrailer: false,
    cC: 0,
    sC: 697,
    isNew: true,
    isHot: false,
    isTicket: true,
    is3D: false,
    isIMAX: false,
    isIMAX3D: false,
    isDMAX: false,
    isPromotion: false
  },
  {
    id: 265865,
    movieId: 265865,
    t: '贝肯熊2：金牌特工',
    year: '2021',
    r: 0,
    rc: 82,
    img: 'http://img5.mtime.cn/mt/2021/05/31/112849.39369805_1280X720X2.jpg',
    m: '',
    actors: '汤水雨 / 孟子焱 / 徐佳琦 / 任亚明',
    p: [
      '动画',
      '冒险'
    ],
    rd: '20210723',
    d: '95分钟',
    rsC: 0,
    ua: 1,
    def: 0,
    commonSpecial: null,
    wantedCount: 393,
    movieType: '动画 / 冒险',
    versions: [
      {
        versionId: 1,
        version: '2D'
      }
    ],
    preferentialFlag: false,
    nearestShowtimeCount: 0,
    nearestCinemaCount: 0,
    nearestDay: 0,
    tCn: '贝肯熊2：金牌特工',
    tEn: 'Agent Backkom：Kings Bear',
    dN: '张扬',
    aN1: null,
    aN2: null,
    isHasTrailer: false,
    cC: 0,
    sC: 535,
    isNew: false,
    isHot: false,
    isTicket: true,
    is3D: false,
    isIMAX: false,
    isIMAX3D: false,
    isDMAX: false,
    isPromotion: false
  },
  {
    id: 266291,
    movieId: 266291,
    t: '危险记忆',
    year: '2021',
    r: 0,
    rc: 6,
    img: 'http://img5.mtime.cn/mt/2021/06/11/112017.25478507_1280X720X2.jpg',
    m: '',
    actors: '甘婷婷 / 李滨 / 乔乔 / 李东翰',
    p: [
      '动作',
      '悬疑',
      '犯罪'
    ],
    rd: '20210806',
    d: '99分钟',
    rsC: 0,
    ua: 1,
    def: 0,
    commonSpecial: null,
    wantedCount: 37,
    movieType: '动作 / 悬疑 / 犯罪',
    versions: [
      {
        versionId: 1,
        version: '2D'
      }
    ],
    preferentialFlag: false,
    nearestShowtimeCount: 0,
    nearestCinemaCount: 0,
    nearestDay: 0,
    tCn: '危险记忆',
    tEn: 'Dangerous Memory',
    dN: '郭大群',
    aN1: '甘婷婷',
    aN2: '李滨',
    isHasTrailer: false,
    cC: 0,
    sC: 332,
    isNew: true,
    isHot: false,
    isTicket: true,
    is3D: false,
    isIMAX: false,
    isIMAX3D: false,
    isDMAX: false,
    isPromotion: false
  },
  {
    id: 266810,
    movieId: 266810,
    t: '皮皮鲁与鲁西西之罐头小人',
    year: '2021',
    r: 0,
    rc: 11,
    img: 'http://img5.mtime.cn/mt/2021/07/09/150433.70895355_1280X720X2.jpg',
    m: '',
    actors: '洪悦熙 / 庄则熙 / 田雨 / 刘一莹',
    p: [
      '喜剧',
      '科幻',
      '儿童'
    ],
    rd: '20210813',
    d: '',
    rsC: 0,
    ua: 1,
    def: 0,
    commonSpecial: null,
    wantedCount: 79,
    movieType: '喜剧 / 科幻 / 儿童',
    versions: null,
    preferentialFlag: false,
    nearestShowtimeCount: 0,
    nearestCinemaCount: 0,
    nearestDay: 0,
    tCn: '皮皮鲁与鲁西西之罐头小人',
    tEn: 'Little Canned Men',
    dN: '于飞',
    aN1: null,
    aN2: null,
    isHasTrailer: false,
    cC: 0,
    sC: 284,
    isNew: true,
    isHot: false,
    isTicket: true,
    is3D: false,
    isIMAX: false,
    isIMAX3D: false,
    isDMAX: false,
    isPromotion: false
  },
  {
    id: 266570,
    movieId: 266570,
    t: '深潜日',
    year: '2020',
    r: 0,
    rc: 0,
    img: 'http://img5.mtime.cn/mt/2019/12/06/173229.98629959_1280X720X2.jpg',
    m: '',
    actors: '李学庆 / 严蔚 / 金鑫',
    p: [
      '剧情',
      '奇幻',
      '悬疑'
    ],
    rd: null,
    d: '90分钟',
    rsC: 0,
    ua: 1,
    def: 0,
    commonSpecial: '',
    wantedCount: 2,
    movieType: '剧情 / 奇幻 / 悬疑',
    versions: [
      {
        versionId: 1,
        version: '2D'
      }
    ],
    preferentialFlag: false,
    nearestShowtimeCount: 0,
    nearestCinemaCount: 0,
    nearestDay: 0,
    tCn: '深潜日',
    tEn: '',
    dN: '金鑫',
    aN1: '李学庆',
    aN2: '严蔚',
    isHasTrailer: false,
    cC: 0,
    sC: 258,
    isNew: false,
    isHot: false,
    isTicket: true,
    is3D: false,
    isIMAX: false,
    isIMAX3D: false,
    isDMAX: false,
    isPromotion: false
  },
  {
    id: 269681,
    movieId: 269681,
    t: '革命者',
    year: '2021',
    r: 7.5,
    rc: 148,
    img: 'http://img5.mtime.cn/mt/2021/07/01/143324.66800351_1280X720X2.jpg',
    m: '',
    actors: '张颂文 / 李易峰 / 佟丽娅 / 彭昱畅',
    p: [
      '剧情',
      '历史'
    ],
    rd: '20210701',
    d: '121分钟',
    rsC: 0,
    ua: 1,
    def: 0,
    commonSpecial: null,
    wantedCount: 170,
    movieType: '剧情 / 历史',
    versions: null,
    preferentialFlag: false,
    nearestShowtimeCount: 0,
    nearestCinemaCount: 0,
    nearestDay: 0,
    tCn: '革命者',
    tEn: 'Pioneer',
    dN: '徐展雄',
    aN1: '张颂文',
    aN2: '李易峰',
    isHasTrailer: false,
    cC: 0,
    sC: 206,
    isNew: false,
    isHot: false,
    isTicket: true,
    is3D: false,
    isIMAX: false,
    isIMAX3D: false,
    isDMAX: false,
    isPromotion: false
  },
  {
    id: 270276,
    movieId: 270276,
    t: '巧虎魔法岛历险记',
    year: '2021',
    r: 0,
    rc: 3,
    img: 'http://img5.mtime.cn/mt/2021/04/29/174242.89203826_1280X720X2.jpg',
    m: '',
    actors: null,
    p: [
      '动画',
      '奇幻',
      '冒险'
    ],
    rd: '20210724',
    d: null,
    rsC: 0,
    ua: 1,
    def: 0,
    commonSpecial: null,
    wantedCount: 177,
    movieType: '动画 / 奇幻 / 冒险',
    versions: [
      {
        versionId: 1,
        version: '2D'
      }
    ],
    preferentialFlag: false,
    nearestShowtimeCount: 0,
    nearestCinemaCount: 0,
    nearestDay: 0,
    tCn: '巧虎魔法岛历险记',
    tEn: '',
    dN: null,
    aN1: null,
    aN2: null,
    isHasTrailer: false,
    cC: 0,
    sC: 121,
    isNew: false,
    isHot: false,
    isTicket: true,
    is3D: false,
    isIMAX: false,
    isIMAX3D: false,
    isDMAX: false,
    isPromotion: false
  },
  {
    id: 267672,
    movieId: 267672,
    t: '新大头儿子和小头爸爸4：完美爸爸',
    year: '2021',
    r: 0,
    rc: 41,
    img: 'http://img5.mtime.cn/mt/2021/04/29/101639.70040839_1280X720X2.jpg',
    m: '',
    actors: '何澄 / 刘可欣',
    p: [
      '动画',
      '冒险',
      '奇幻'
    ],
    rd: '20210709',
    d: '85分钟',
    rsC: 0,
    ua: 1,
    def: 0,
    commonSpecial: null,
    wantedCount: 134,
    movieType: '动画 / 冒险 / 奇幻',
    versions: [
      {
        versionId: 1,
        version: '2D'
      }
    ],
    preferentialFlag: false,
    nearestShowtimeCount: 0,
    nearestCinemaCount: 0,
    nearestDay: 0,
    tCn: '新大头儿子和小头爸爸4：完美爸爸',
    tEn: 'New Happy Dad and Son 4',
    dN: '何澄,刘可欣',
    aN1: null,
    aN2: null,
    isHasTrailer: false,
    cC: 0,
    sC: 109,
    isNew: false,
    isHot: false,
    isTicket: true,
    is3D: false,
    isIMAX: false,
    isIMAX3D: false,
    isDMAX: false,
    isPromotion: false
  },
  {
    id: 267938,
    movieId: 267938,
    t: '1921',
    year: '2021',
    r: 7,
    rc: 287,
    img: 'http://img5.mtime.cn/mt/2021/04/13/154328.31480704_1280X720X2.jpg',
    m: '',
    actors: '黄轩 / 倪妮 / 王仁君 / 刘昊然',
    p: [
      '剧情'
    ],
    rd: '20210701',
    d: '137分钟',
    rsC: 0,
    ua: 1,
    def: 0,
    commonSpecial: null,
    wantedCount: 412,
    movieType: '剧情',
    versions: null,
    preferentialFlag: false,
    nearestShowtimeCount: 0,
    nearestCinemaCount: 0,
    nearestDay: 0,
    tCn: '1921',
    tEn: '1921',
    dN: '黄建新,郑大圣',
    aN1: '黄轩',
    aN2: '郑大圣',
    isHasTrailer: false,
    cC: 0,
    sC: 105,
    isNew: false,
    isHot: false,
    isTicket: true,
    is3D: false,
    isIMAX: false,
    isIMAX3D: false,
    isDMAX: false,
    isPromotion: false
  },
  {
    id: 266586,
    movieId: 266586,
    t: '困在时间里的父亲',
    year: '2020',
    r: 8.3,
    rc: 423,
    img: 'http://img5.mtime.cn/mt/2021/06/02/173812.99268898_1280X720X2.jpg',
    m: '',
    actors: '安东尼·霍普金斯 / 奥莉薇娅·柯尔曼 / 奥莉维亚·威廉姆斯 / 伊莫珍·波茨',
    p: [
      '剧情'
    ],
    rd: '20210618',
    d: '97分钟',
    rsC: 0,
    ua: 1,
    def: 0,
    commonSpecial: null,
    wantedCount: 347,
    movieType: '剧情',
    versions: null,
    preferentialFlag: false,
    nearestShowtimeCount: 0,
    nearestCinemaCount: 0,
    nearestDay: 0,
    tCn: '困在时间里的父亲',
    tEn: 'The Father',
    dN: '佛罗莱恩·泽勒',
    aN1: '安东尼·霍普金斯',
    aN2: '奥莉薇娅·柯尔曼',
    isHasTrailer: false,
    cC: 0,
    sC: 101,
    isNew: false,
    isHot: false,
    isTicket: true,
    is3D: false,
    isIMAX: false,
    isIMAX3D: false,
    isDMAX: false,
    isPromotion: false
  },
  {
    id: 269783,
    movieId: 269783,
    t: '燃野少年的天空',
    year: '2021',
    r: 5.7,
    rc: 132,
    img: 'http://img5.mtime.cn/mt/2021/07/05/104210.35224552_1280X720X2.jpg',
    m: '',
    actors: '彭昱畅 / 许恩怡 / 张宥浩 / 尹正',
    p: [
      '歌舞',
      '喜剧'
    ],
    rd: '20210717',
    d: '108分钟',
    rsC: 0,
    ua: 1,
    def: 0,
    commonSpecial: null,
    wantedCount: 96,
    movieType: '歌舞 / 喜剧',
    versions: null,
    preferentialFlag: false,
    nearestShowtimeCount: 0,
    nearestCinemaCount: 0,
    nearestDay: 0,
    tCn: '燃野少年的天空',
    tEn: 'The Day We Lit Up The Sky',
    dN: '张一白,韩琰',
    aN1: '彭昱畅',
    aN2: '张宥浩',
    isHasTrailer: false,
    cC: 0,
    sC: 79,
    isNew: false,
    isHot: false,
    isTicket: true,
    is3D: false,
    isIMAX: false,
    isIMAX3D: false,
    isDMAX: false,
    isPromotion: false
  },
  {
    id: 242185,
    movieId: 242185,
    t: '狼行者',
    year: '2020',
    r: 7.8,
    rc: 143,
    img: 'http://img5.mtime.cn/mt/2021/06/02/143546.58967996_1280X720X2.jpg',
    m: '',
    actors: '奥诺·科尼弗塞 / Eva Whittaker / 肖恩·宾 / 西蒙·迈克伯尼',
    p: [
      '动画',
      '冒险',
      '家庭'
    ],
    rd: '20210703',
    d: '1h 43min',
    rsC: 0,
    ua: 1,
    def: 0,
    commonSpecial: null,
    wantedCount: 117,
    movieType: '动画 / 冒险 / 家庭',
    versions: null,
    preferentialFlag: false,
    nearestShowtimeCount: 0,
    nearestCinemaCount: 0,
    nearestDay: 0,
    tCn: '狼行者',
    tEn: 'Wolfwalkers',
    dN: '汤姆·摩尔,Ross Stewart',
    aN1: '奥诺·科尼弗塞',
    aN2: 'Eva Whittaker',
    isHasTrailer: false,
    cC: 0,
    sC: 62,
    isNew: false,
    isHot: false,
    isTicket: true,
    is3D: false,
    isIMAX: false,
    isIMAX3D: false,
    isDMAX: false,
    isPromotion: false
  },
  {
    id: 262578,
    movieId: 262578,
    t: '你好世界',
    year: '2019',
    r: 7.4,
    rc: 169,
    img: 'http://img5.mtime.cn/mt/2021/06/20/231741.89878008_1280X720X2.jpg',
    m: '',
    actors: '北村匠海 / 滨边美波 / 松坂桃李 / 福原遥',
    p: [
      '动画',
      '爱情',
      '科幻'
    ],
    rd: '20210611',
    d: '',
    rsC: 0,
    ua: 1,
    def: 0,
    commonSpecial: null,
    wantedCount: 312,
    movieType: '动画 / 爱情 / 科幻',
    versions: null,
    preferentialFlag: false,
    nearestShowtimeCount: 0,
    nearestCinemaCount: 0,
    nearestDay: 0,
    tCn: '你好世界',
    tEn: 'Hello World',
    dN: '伊藤智彦',
    aN1: '北村匠海',
    aN2: '滨边美波',
    isHasTrailer: false,
    cC: 0,
    sC: 55,
    isNew: false,
    isHot: false,
    isTicket: true,
    is3D: false,
    isIMAX: false,
    isIMAX3D: false,
    isDMAX: false,
    isPromotion: false
  },
  {
    id: 270381,
    movieId: 270381,
    t: '大学',
    year: '2021',
    r: 0,
    rc: 17,
    img: 'http://img5.mtime.cn/mt/2021/06/11/115301.79155425_1280X720X2.jpg',
    m: '',
    actors: '钱易 / 蔡峥 / 宋云天 / 严韫洲',
    p: [
      '纪录片'
    ],
    rd: '20210709',
    d: null,
    rsC: 0,
    ua: 1,
    def: 0,
    commonSpecial: null,
    wantedCount: 57,
    movieType: '纪录片',
    versions: null,
    preferentialFlag: false,
    nearestShowtimeCount: 0,
    nearestCinemaCount: 0,
    nearestDay: 0,
    tCn: '大学',
    tEn: 'The Great Learning',
    dN: '孙虹,王静',
    aN1: null,
    aN2: null,
    isHasTrailer: false,
    cC: 0,
    sC: 54,
    isNew: false,
    isHot: false,
    isTicket: true,
    is3D: false,
    isIMAX: false,
    isIMAX3D: false,
    isDMAX: false,
    isPromotion: false
  },
  {
    id: 11982,
    movieId: 11982,
    t: '天堂电影院',
    year: '1988',
    r: 8.8,
    rc: 17774,
    img: 'http://img5.mtime.cn/mt/2021/05/28/114904.50012589_1280X720X2.jpg',
    m: '',
    actors: '菲利浦·诺瓦雷 / 萨瓦特利·卡西欧 / 马克·莱昂纳蒂 / 艾格尼丝·娜诺',
    p: [
      '剧情'
    ],
    rd: '20210611',
    d: '155 min',
    rsC: 0,
    ua: 1,
    def: 0,
    commonSpecial: null,
    wantedCount: 5978,
    movieType: '剧情',
    versions: null,
    preferentialFlag: false,
    nearestShowtimeCount: 0,
    nearestCinemaCount: 0,
    nearestDay: 0,
    tCn: '天堂电影院',
    tEn: 'Nuovo cinema Paradiso',
    dN: '朱塞佩·托纳多雷',
    aN1: '菲利浦·诺瓦雷',
    aN2: '萨瓦特利·卡西欧',
    isHasTrailer: false,
    cC: 0,
    sC: 53,
    isNew: false,
    isHot: false,
    isTicket: true,
    is3D: false,
    isIMAX: false,
    isIMAX3D: false,
    isDMAX: false,
    isPromotion: false
  },
  {
    id: 264833,
    movieId: 264833,
    t: '普罗米亚',
    year: '2019',
    r: 7.6,
    rc: 116,
    img: 'http://img5.mtime.cn/mt/2021/05/26/105845.34249572_1280X720X2.jpg',
    m: '',
    actors: '古田新太 / 桧山修之 / Tetsu Inada / 小林剑道',
    p: [
      '动画',
      '冒险',
      '科幻'
    ],
    rd: '20210605',
    d: '1h 51min',
    rsC: 0,
    ua: 1,
    def: 0,
    commonSpecial: null,
    wantedCount: 69,
    movieType: '动画 / 冒险 / 科幻',
    versions: null,
    preferentialFlag: false,
    nearestShowtimeCount: 0,
    nearestCinemaCount: 0,
    nearestDay: 0,
    tCn: '普罗米亚',
    tEn: 'Promare',
    dN: '今石洋之',
    aN1: '古田新太',
    aN2: '桧山修之',
    isHasTrailer: false,
    cC: 0,
    sC: 43,
    isNew: false,
    isHot: false,
    isTicket: true,
    is3D: false,
    isIMAX: false,
    isIMAX3D: false,
    isDMAX: false,
    isPromotion: false
  },
  {
    id: 262571,
    movieId: 262571,
    t: '西游记之再世妖王',
    year: '2021',
    r: 6,
    rc: 81,
    img: 'http://img5.mtime.cn/mt/2021/07/28/163717.89627078_1280X720X2.jpg',
    m: '',
    actors: '边江 / 张磊 / 蔡海婷 / 苏尚卿',
    p: [
      '动画',
      '动作',
      '奇幻'
    ],
    rd: '20210402',
    d: '95分钟',
    rsC: 0,
    ua: 1,
    def: 0,
    commonSpecial: null,
    wantedCount: 264,
    movieType: '动画 / 动作 / 奇幻',
    versions: null,
    preferentialFlag: false,
    nearestShowtimeCount: 0,
    nearestCinemaCount: 0,
    nearestDay: 0,
    tCn: '西游记之再世妖王',
    tEn: 'Monkey King Reborn',
    dN: '王云飞',
    aN1: null,
    aN2: null,
    isHasTrailer: false,
    cC: 0,
    sC: 43,
    isNew: false,
    isHot: false,
    isTicket: true,
    is3D: false,
    isIMAX: false,
    isIMAX3D: false,
    isDMAX: false,
    isPromotion: false
  },
  {
    id: 270265,
    movieId: 270265,
    t: '爱情来时',
    year: '2021',
    r: 0,
    rc: 0,
    img: 'http://img5.mtime.cn/mt/2021/04/27/113711.72680550_1280X720X2.jpg',
    m: '',
    actors: '石靖怡 / 喻大维 / 郑红',
    p: [
      '爱情'
    ],
    rd: '20210430',
    d: '88',
    rsC: 0,
    ua: 1,
    def: 0,
    commonSpecial: null,
    wantedCount: 0,
    movieType: '爱情',
    versions: [
      {
        versionId: 1,
        version: '2D'
      }
    ],
    preferentialFlag: false,
    nearestShowtimeCount: 0,
    nearestCinemaCount: 0,
    nearestDay: 0,
    tCn: '爱情来时',
    tEn: '',
    dN: '郑红',
    aN1: null,
    aN2: null,
    isHasTrailer: false,
    cC: 0,
    sC: 27,
    isNew: false,
    isHot: false,
    isTicket: true,
    is3D: false,
    isIMAX: false,
    isIMAX3D: false,
    isDMAX: false,
    isPromotion: false
  },
  {
    id: 268500,
    movieId: 268500,
    t: '当男人恋爱时',
    year: '2021',
    r: 6.6,
    rc: 121,
    img: 'http://img5.mtime.cn/mt/2021/05/28/164416.92806064_1280X720X2.jpg',
    m: '',
    actors: '邱泽 / 许玮甯 / 蔡振南 / 钟欣凌',
    p: [
      '爱情'
    ],
    rd: '20210611',
    d: '115分钟',
    rsC: 0,
    ua: 1,
    def: 0,
    commonSpecial: null,
    wantedCount: 146,
    movieType: '爱情',
    versions: null,
    preferentialFlag: false,
    nearestShowtimeCount: 0,
    nearestCinemaCount: 0,
    nearestDay: 0,
    tCn: '当男人恋爱时',
    tEn: 'Man in Love',
    dN: '殷振豪',
    aN1: '邱泽',
    aN2: '许玮甯',
    isHasTrailer: false,
    cC: 0,
    sC: 27,
    isNew: false,
    isHot: false,
    isTicket: true,
    is3D: false,
    isIMAX: false,
    isIMAX3D: false,
    isDMAX: false,
    isPromotion: false
  },
  {
    id: 264116,
    movieId: 264116,
    t: '俑之城',
    year: '2021',
    r: 0,
    rc: 65,
    img: 'http://img5.mtime.cn/mt/2021/06/28/164630.47464388_1280X720X2.jpg',
    m: '',
    actors: '朱光祖 / 张茗 / 周子瑜 / 谭笑',
    p: [
      '爱情',
      '动画',
      '奇幻'
    ],
    rd: '20210709',
    d: '111分钟',
    rsC: 0,
    ua: 1,
    def: 0,
    commonSpecial: null,
    wantedCount: 89,
    movieType: '爱情 / 动画 / 奇幻',
    versions: [
      {
        versionId: 1,
        version: '2D'
      }
    ],
    preferentialFlag: false,
    nearestShowtimeCount: 0,
    nearestCinemaCount: 0,
    nearestDay: 0,
    tCn: '俑之城',
    tEn: 'Realm of Terracotta',
    dN: '丁亮,林永长',
    aN1: null,
    aN2: null,
    isHasTrailer: false,
    cC: 0,
    sC: 25,
    isNew: false,
    isHot: false,
    isTicket: true,
    is3D: false,
    isIMAX: false,
    isIMAX3D: false,
    isDMAX: false,
    isPromotion: false
  },
  {
    id: 270466,
    movieId: 270466,
    t: '济公之降龙降世',
    year: '2021',
    r: 0,
    rc: 40,
    img: 'http://img5.mtime.cn/mt/2021/06/10/094426.31545414_1280X720X2.jpg',
    m: '',
    actors: '刘志江 / 乔彧 / 张挺 / 孙武',
    p: [
      '动画',
      '奇幻',
      '冒险'
    ],
    rd: '20210716',
    d: '92',
    rsC: 0,
    ua: 1,
    def: 0,
    commonSpecial: null,
    wantedCount: 59,
    movieType: '动画 / 奇幻 / 冒险',
    versions: null,
    preferentialFlag: false,
    nearestShowtimeCount: 0,
    nearestCinemaCount: 0,
    nearestDay: 0,
    tCn: '济公之降龙降世',
    tEn: 'Master Ji Gong',
    dN: '刘志江,乔彧',
    aN1: null,
    aN2: null,
    isHasTrailer: false,
    cC: 0,
    sC: 23,
    isNew: false,
    isHot: false,
    isTicket: true,
    is3D: false,
    isIMAX: false,
    isIMAX3D: false,
    isDMAX: false,
    isPromotion: false
  },
  {
    id: 265517,
    movieId: 265517,
    t: '直立象传说',
    year: '2021',
    r: 0,
    rc: 5,
    img: 'http://img5.mtime.cn/mt/2021/07/05/092244.54188321_1280X720X2.jpg',
    m: '',
    actors: '特穆拉·莫里森 / 露西·劳莱丝 / 约翰·里斯-戴维斯 / 瑞斯·达比',
    p: [
      '动画',
      '奇幻',
      '冒险'
    ],
    rd: '20210730',
    d: '98分钟',
    rsC: 0,
    ua: 1,
    def: 0,
    commonSpecial: null,
    wantedCount: 49,
    movieType: '动画 / 奇幻 / 冒险',
    versions: [
      {
        versionId: 1,
        version: '2D'
      }
    ],
    preferentialFlag: false,
    nearestShowtimeCount: 0,
    nearestCinemaCount: 0,
    nearestDay: 0,
    tCn: '直立象传说',
    tEn: 'Mosley',
    dN: '黄军,柯比·阿特金斯',
    aN1: '特穆拉·莫里森',
    aN2: '露西·劳莱丝',
    isHasTrailer: false,
    cC: 0,
    sC: 19,
    isNew: false,
    isHot: false,
    isTicket: true,
    is3D: false,
    isIMAX: false,
    isIMAX3D: false,
    isDMAX: false,
    isPromotion: false
  },
  {
    id: 270427,
    movieId: 270427,
    t: '拯救甜甜圈：时空大营救',
    year: '2021',
    r: 0,
    rc: 4,
    img: 'http://img5.mtime.cn/mt/2021/08/03/100311.56361391_1280X720X2.jpg',
    m: '',
    actors: '亚当·德维恩 / 蕾切尔·布鲁姆 / 肯·郑 / 莎姬·贝兹',
    p: [
      '动画',
      '家庭',
      '冒险'
    ],
    rd: null,
    d: '84分钟',
    rsC: 0,
    ua: 1,
    def: 0,
    commonSpecial: null,
    wantedCount: 34,
    movieType: '动画 / 家庭 / 冒险',
    versions: null,
    preferentialFlag: false,
    nearestShowtimeCount: 0,
    nearestCinemaCount: 0,
    nearestDay: 0,
    tCn: '拯救甜甜圈：时空大营救',
    tEn: 'Extinct',
    dN: '大卫·斯沃曼,雷蒙德·S·珀斯',
    aN1: null,
    aN2: null,
    isHasTrailer: false,
    cC: 0,
    sC: 15,
    isNew: false,
    isHot: false,
    isTicket: true,
    is3D: false,
    isIMAX: false,
    isIMAX3D: false,
    isDMAX: false,
    isPromotion: false
  },
  {
    id: 249790,
    movieId: 249790,
    t: '终极代码',
    year: '2021',
    r: 0,
    rc: 9,
    img: 'http://img5.mtime.cn/mt/2021/07/13/144926.20567316_1280X720X2.jpg',
    m: '',
    actors: '吴治廷 / 孟璐 / 大卫·贝尔 / 狼森',
    p: [
      '动作',
      '冒险',
      '惊悚'
    ],
    rd: '20210716',
    d: '92分钟',
    rsC: 0,
    ua: 1,
    def: 0,
    commonSpecial: null,
    wantedCount: 35,
    movieType: '动作 / 冒险 / 惊悚',
    versions: [
      {
        versionId: 1,
        version: '2D'
      }
    ],
    preferentialFlag: false,
    nearestShowtimeCount: 0,
    nearestCinemaCount: 0,
    nearestDay: 0,
    tCn: '终极代码',
    tEn: 'Ultimate Code',
    dN: '吴治廷',
    aN1: '吴治廷',
    aN2: '孟璐',
    isHasTrailer: false,
    cC: 0,
    sC: 14,
    isNew: false,
    isHot: false,
    isTicket: true,
    is3D: false,
    isIMAX: false,
    isIMAX3D: false,
    isDMAX: false,
    isPromotion: false
  },
  {
    id: 266839,
    movieId: 266839,
    t: '人之怒',
    year: '2021',
    r: 7,
    rc: 668,
    img: 'http://img5.mtime.cn/mt/2021/04/28/133222.78526355_1280X720X2.jpg',
    m: '',
    actors: '杰森·斯坦森 / 乔什·哈奈特 / 霍特·麦克卡兰尼 / 斯科特·伊斯特伍德',
    p: [
      '动作',
      '犯罪'
    ],
    rd: '20210510',
    d: '中国115分钟/美国118分钟',
    rsC: 0,
    ua: 1,
    def: 0,
    commonSpecial: null,
    wantedCount: 443,
    movieType: '动作 / 犯罪',
    versions: null,
    preferentialFlag: false,
    nearestShowtimeCount: 0,
    nearestCinemaCount: 0,
    nearestDay: 0,
    tCn: '人之怒',
    tEn: 'Wrath of Man',
    dN: '盖·里奇',
    aN1: '杰森·斯坦森',
    aN2: '乔什·哈奈特',
    isHasTrailer: false,
    cC: 0,
    sC: 13,
    isNew: false,
    isHot: false,
    isTicket: true,
    is3D: false,
    isIMAX: false,
    isIMAX3D: false,
    isDMAX: false,
    isPromotion: false
  },
  {
    id: 15541,
    movieId: 15541,
    t: '地道战',
    year: '1966',
    r: 7.6,
    rc: 1246,
    img: 'http://img31.mtime.cn/mt/2015/05/08/172146.80215032_1280X720X2.jpg',
    m: '',
    actors: '朱龙广 / 王炳彧 / 张勇手 / 刘秀杰',
    p: [
      '战争'
    ],
    rd: '19660101',
    d: '102 min',
    rsC: 0,
    ua: 1,
    def: 0,
    commonSpecial: null,
    wantedCount: 45,
    movieType: '战争',
    versions: null,
    preferentialFlag: false,
    nearestShowtimeCount: 0,
    nearestCinemaCount: 0,
    nearestDay: 0,
    tCn: '地道战',
    tEn: 'Tunnel Warfare',
    dN: '任旭东',
    aN1: '朱龙广',
    aN2: '王炳彧',
    isHasTrailer: false,
    cC: 0,
    sC: 12,
    isNew: false,
    isHot: false,
    isTicket: true,
    is3D: false,
    isIMAX: false,
    isIMAX3D: false,
    isDMAX: false,
    isPromotion: false
  },
  {
    id: 266622,
    movieId: 266622,
    t: '哆啦A梦：伴我同行2',
    year: '2020',
    r: 7.6,
    rc: 262,
    img: 'http://img5.mtime.cn/mt/2021/04/14/100352.99938324_1280X720X2.jpg',
    m: '',
    actors: '妻夫木聪 / 宫本信子 / 八木龙一 / 山崎贵',
    p: [
      '动画'
    ],
    rd: '20210528',
    d: '96',
    rsC: 0,
    ua: 1,
    def: 0,
    commonSpecial: null,
    wantedCount: 562,
    movieType: '动画',
    versions: [
      {
        versionId: 1,
        version: '2D'
      }
    ],
    preferentialFlag: false,
    nearestShowtimeCount: 0,
    nearestCinemaCount: 0,
    nearestDay: 0,
    tCn: '哆啦A梦：伴我同行2',
    tEn: '',
    dN: '山崎贵',
    aN1: '妻夫木聪',
    aN2: '宫本信子',
    isHasTrailer: false,
    cC: 0,
    sC: 10,
    isNew: false,
    isHot: false,
    isTicket: true,
    is3D: false,
    isIMAX: false,
    isIMAX3D: false,
    isDMAX: false,
    isPromotion: false
  },
  {
    id: 33061,
    movieId: 33061,
    t: '狼牙山五壮士',
    year: '1958',
    r: 7.2,
    rc: 614,
    img: 'http://img31.mtime.cn/mt/2014/02/23/025347.52232633_1280X720X2.jpg',
    m: '',
    actors: '高保成 / 李长华 / 李力 / 张怀志',
    p: [
      '战争'
    ],
    rd: null,
    d: '',
    rsC: 0,
    ua: 1,
    def: 0,
    commonSpecial: null,
    wantedCount: 21,
    movieType: '战争',
    versions: null,
    preferentialFlag: false,
    nearestShowtimeCount: 0,
    nearestCinemaCount: 0,
    nearestDay: 0,
    tCn: '狼牙山五壮士',
    tEn: 'Langya shan wu zhuang shi',
    dN: '史文炽',
    aN1: '高保成',
    aN2: '李长华',
    isHasTrailer: false,
    cC: 0,
    sC: 9,
    isNew: false,
    isHot: false,
    isTicket: true,
    is3D: false,
    isIMAX: false,
    isIMAX3D: false,
    isDMAX: false,
    isPromotion: false
  },
  {
    id: 270225,
    movieId: 270225,
    t: '白蛇传·情',
    year: '2021',
    r: 8.5,
    rc: 155,
    img: 'http://img5.mtime.cn/mt/2021/05/24/153018.91601847_1280X720X2.jpg',
    m: '',
    actors: '曾小敏 / 文汝清 / 王燕飞 / 朱红星',
    p: [
      '戏曲'
    ],
    rd: '20210520',
    d: '101',
    rsC: 0,
    ua: 1,
    def: 0,
    commonSpecial: null,
    wantedCount: 167,
    movieType: '戏曲',
    versions: [
      {
        versionId: 1,
        version: '2D'
      }
    ],
    preferentialFlag: false,
    nearestShowtimeCount: 0,
    nearestCinemaCount: 0,
    nearestDay: 0,
    tCn: '白蛇传·情',
    tEn: 'White Snake',
    dN: '张险峰',
    aN1: null,
    aN2: null,
    isHasTrailer: false,
    cC: 0,
    sC: 8,
    isNew: false,
    isHot: false,
    isTicket: true,
    is3D: false,
    isIMAX: false,
    isIMAX3D: false,
    isDMAX: false,
    isPromotion: false
  },
  {
    id: 11600,
    movieId: 11600,
    t: '情书',
    year: '1995',
    r: 8.4,
    rc: 15438,
    img: 'http://img5.mtime.cn/mt/2021/04/29/100015.54134616_1280X720X2.jpg',
    m: '',
    actors: '中山美穗 / 柏原崇 / 酒井美纪 / 丰川悦司',
    p: [
      '剧情',
      '爱情'
    ],
    rd: '20210520',
    d: '117 min',
    rsC: 0,
    ua: 1,
    def: 0,
    commonSpecial: null,
    wantedCount: 3837,
    movieType: '剧情 / 爱情',
    versions: null,
    preferentialFlag: false,
    nearestShowtimeCount: 0,
    nearestCinemaCount: 0,
    nearestDay: 0,
    tCn: '情书',
    tEn: 'Love Letter',
    dN: '岩井俊二',
    aN1: '中山美穗',
    aN2: '柏原崇',
    isHasTrailer: false,
    cC: 0,
    sC: 7,
    isNew: false,
    isHot: false,
    isTicket: true,
    is3D: false,
    isIMAX: false,
    isIMAX3D: false,
    isDMAX: false,
    isPromotion: false
  },
  {
    id: 270321,
    movieId: 270321,
    t: '五个扑水的少年',
    year: '2021',
    r: 0,
    rc: 7,
    img: 'http://img5.mtime.cn/mt/2021/05/13/102555.24809281_1280X720X2.jpg',
    m: '',
    actors: '辛云来 / 冯祥琨 / 李孝谦 / 王川',
    p: [
      '剧情',
      '喜剧'
    ],
    rd: '20210813',
    d: null,
    rsC: 0,
    ua: 1,
    def: 0,
    commonSpecial: null,
    wantedCount: 47,
    movieType: '剧情 / 喜剧',
    versions: null,
    preferentialFlag: false,
    nearestShowtimeCount: 0,
    nearestCinemaCount: 0,
    nearestDay: 0,
    tCn: '五个扑水的少年',
    tEn: 'Water Boys',
    dN: '宋灏霖',
    aN1: null,
    aN2: null,
    isHasTrailer: false,
    cC: 0,
    sC: 6,
    isNew: true,
    isHot: false,
    isTicket: true,
    is3D: false,
    isIMAX: false,
    isIMAX3D: false,
    isDMAX: false,
    isPromotion: false
  },
  {
    id: 270628,
    movieId: 270628,
    t: '站着等你三千年',
    year: '2021',
    r: 0,
    rc: 1,
    img: 'http://img5.mtime.cn/mt/2021/07/12/152245.68125143_1280X720X2.jpg',
    m: '',
    actors: '厉家兵 / 陈俊亨 / 李鑫雨 / 梁霆炜',
    p: [
      '爱情',
      '剧情'
    ],
    rd: '20210731',
    d: '102分钟',
    rsC: 0,
    ua: 1,
    def: 0,
    commonSpecial: null,
    wantedCount: 7,
    movieType: '爱情 / 剧情',
    versions: null,
    preferentialFlag: false,
    nearestShowtimeCount: 0,
    nearestCinemaCount: 0,
    nearestDay: 0,
    tCn: '站着等你三千年',
    tEn: '',
    dN: '刘云舟',
    aN1: null,
    aN2: null,
    isHasTrailer: false,
    cC: 0,
    sC: 5,
    isNew: true,
    isHot: false,
    isTicket: true,
    is3D: false,
    isIMAX: false,
    isIMAX3D: false,
    isDMAX: false,
    isPromotion: false
  },
  {
    id: 270420,
    movieId: 270420,
    t: '完美受害人',
    year: '2021',
    r: 7.3,
    rc: 101,
    img: 'http://img5.mtime.cn/mt/2021/06/02/101834.78068703_1280X720X2.jpg',
    m: '',
    actors: '李乃文 / 冯文娟 / 张峻宁 / 谭凯',
    p: [
      '剧情',
      '犯罪'
    ],
    rd: '20210625',
    d: '101分钟',
    rsC: 0,
    ua: 1,
    def: 0,
    commonSpecial: null,
    wantedCount: 40,
    movieType: '剧情 / 犯罪',
    versions: null,
    preferentialFlag: false,
    nearestShowtimeCount: 0,
    nearestCinemaCount: 0,
    nearestDay: 0,
    tCn: '完美受害人',
    tEn: 'The Perfect Victim',
    dN: '杨泷杰',
    aN1: null,
    aN2: null,
    isHasTrailer: false,
    cC: 0,
    sC: 5,
    isNew: false,
    isHot: false,
    isTicket: true,
    is3D: false,
    isIMAX: false,
    isIMAX3D: false,
    isDMAX: false,
    isPromotion: false
  },
  {
    id: 270428,
    movieId: 270428,
    t: '守岛人',
    year: '2021',
    r: 8,
    rc: 94,
    img: 'http://img5.mtime.cn/mt/2021/06/03/093725.30789902_1280X720X2.jpg',
    m: '',
    actors: '刘烨 / 宫哲 / 侯勇 / 孙维民',
    p: [
      '剧情'
    ],
    rd: '20210618',
    d: '125分钟',
    rsC: 0,
    ua: 1,
    def: 0,
    commonSpecial: null,
    wantedCount: 77,
    movieType: '剧情',
    versions: null,
    preferentialFlag: false,
    nearestShowtimeCount: 0,
    nearestCinemaCount: 0,
    nearestDay: 0,
    tCn: '守岛人',
    tEn: 'Island Keeper',
    dN: '陈力',
    aN1: null,
    aN2: null,
    isHasTrailer: false,
    cC: 0,
    sC: 5,
    isNew: false,
    isHot: false,
    isTicket: true,
    is3D: false,
    isIMAX: false,
    isIMAX3D: false,
    isDMAX: false,
    isPromotion: false
  },
  {
    id: 240425,
    movieId: 240425,
    t: '红海行动',
    year: '2018',
    r: 8.6,
    rc: 10523,
    img: 'http://img5.mtime.cn/mt/2018/02/17/150049.57218452_1280X720X2.jpg',
    m: '',
    actors: '张译 / 黄景瑜 / 海清 / 杜江',
    p: [
      '动作',
      '剧情'
    ],
    rd: '20180216',
    d: '138分钟',
    rsC: 0,
    ua: 1,
    def: 0,
    commonSpecial: '"蛟龙突击队"演绎神兵天降',
    wantedCount: 3665,
    movieType: '动作 / 剧情',
    versions: [
      {
        versionId: 1,
        version: '2D'
      },
      {
        versionId: 2,
        version: '3D'
      },
      {
        versionId: 4,
        version: 'IMAX3D'
      },
      {
        versionId: 6,
        version: '中国巨幕'
      }
    ],
    preferentialFlag: false,
    nearestShowtimeCount: 0,
    nearestCinemaCount: 0,
    nearestDay: 0,
    tCn: '红海行动',
    tEn: 'Operation Red Sea',
    dN: '林超贤',
    aN1: '张译',
    aN2: '黄景瑜',
    isHasTrailer: false,
    cC: 0,
    sC: 4,
    isNew: false,
    isHot: false,
    isTicket: true,
    is3D: true,
    isIMAX: false,
    isIMAX3D: true,
    isDMAX: true,
    isPromotion: false
  },
  {
    id: 229733,
    movieId: 229733,
    t: '战狼2',
    year: '2017',
    r: 8.5,
    rc: 17362,
    img: 'http://img5.mtime.cn/mt/2020/07/21/153448.87663608_1280X720X2.jpg',
    m: '',
    actors: '吴京 / 弗兰克·格里罗 / 赵毅 / 吴刚',
    p: [
      '动作',
      '战争'
    ],
    rd: '20180919',
    d: '123分钟',
    rsC: 0,
    ua: 1,
    def: 0,
    commonSpecial: '吴京领衔坦克版速度与激情',
    wantedCount: 9361,
    movieType: '动作 / 战争',
    versions: [
      {
        versionId: 1,
        version: '2D'
      },
      {
        versionId: 2,
        version: '3D'
      },
      {
        versionId: 3,
        version: 'IMAX'
      },
      {
        versionId: 6,
        version: '中国巨幕'
      }
    ],
    preferentialFlag: false,
    nearestShowtimeCount: 0,
    nearestCinemaCount: 0,
    nearestDay: 0,
    tCn: '战狼2',
    tEn: 'Wolf Warriors Ⅱ',
    dN: '吴京',
    aN1: '吴京',
    aN2: '弗兰克·格里罗',
    isHasTrailer: false,
    cC: 0,
    sC: 4,
    isNew: false,
    isHot: false,
    isTicket: true,
    is3D: true,
    isIMAX: true,
    isIMAX3D: false,
    isDMAX: true,
    isPromotion: false
  },
  {
    id: 218219,
    movieId: 218219,
    t: '潜艇总动员：时光宝盒',
    year: '2015',
    r: 5.6,
    rc: 115,
    img: 'http://img5.mtime.cn/mt/2017/05/05/175827.41424421_1280X720X2.jpg',
    m: '',
    actors: '范楚绒 / 洪海天 / 谢元真 / 王燕华',
    p: [
      '动画',
      '喜剧',
      '冒险'
    ],
    rd: '20150529',
    d: '80分钟',
    rsC: 0,
    ua: 1,
    def: 0,
    commonSpecial: '萌版超级英雄拯救海底',
    wantedCount: 455,
    movieType: '动画 / 喜剧 / 冒险',
    versions: [
      {
        versionId: 1,
        version: '2D'
      },
      {
        versionId: 2,
        version: '3D'
      }
    ],
    preferentialFlag: false,
    nearestShowtimeCount: 0,
    nearestCinemaCount: 0,
    nearestDay: 0,
    tCn: '潜艇总动员：时光宝盒',
    tEn: 'Happy Little Submarine Magic Box of Time',
    dN: '何子力',
    aN1: '范楚绒',
    aN2: '洪海天',
    isHasTrailer: false,
    cC: 0,
    sC: 3,
    isNew: false,
    isHot: false,
    isTicket: true,
    is3D: true,
    isIMAX: false,
    isIMAX3D: false,
    isDMAX: false,
    isPromotion: false
  },
  {
    id: 211793,
    movieId: 211793,
    t: '潜艇总动员4：章鱼奇遇记',
    year: '2014',
    r: 5.2,
    rc: 528,
    img: 'http://img31.mtime.cn/mt/2014/05/20/095416.39889053_1280X720X2.jpg',
    m: '',
    actors: '蒋可 / 王晓彤 / 李晔 / 孙宁芳',
    p: [
      '动画',
      '冒险',
      '喜剧'
    ],
    rd: '20140530',
    d: '80分钟',
    rsC: 0,
    ua: 1,
    def: 0,
    commonSpecial: '给小孩讲这么人艰不拆的故事好么？',
    wantedCount: 39,
    movieType: '动画 / 冒险 / 喜剧',
    versions: [
      {
        versionId: 2,
        version: '3D'
      }
    ],
    preferentialFlag: false,
    nearestShowtimeCount: 0,
    nearestCinemaCount: 0,
    nearestDay: 0,
    tCn: '潜艇总动员4：章鱼奇遇记',
    tEn: 'Happy Little Submarines 4 : Adventure of Octopus',
    dN: '何子力',
    aN1: '蒋可',
    aN2: '王晓彤',
    isHasTrailer: false,
    cC: 0,
    sC: 3,
    isNew: false,
    isHot: false,
    isTicket: true,
    is3D: true,
    isIMAX: false,
    isIMAX3D: false,
    isDMAX: false,
    isPromotion: false
  },
  {
    id: 254656,
    movieId: 254656,
    t: '潜艇总动员：海底两万里',
    year: '2018',
    r: 5.9,
    rc: 49,
    img: 'http://img5.mtime.cn/mt/2018/05/24/112442.80786906_1280X720X2.jpg',
    m: '',
    actors: '范楚绒 / 洪海天 / 李晔 / 谭满堂',
    p: [
      '动画'
    ],
    rd: '20180601',
    d: '75分钟',
    rsC: 0,
    ua: 1,
    def: 0,
    commonSpecial: '小潜艇阿力的海底大冒险',
    wantedCount: 268,
    movieType: '动画',
    versions: [
      {
        versionId: 1,
        version: '2D'
      },
      {
        versionId: 2,
        version: '3D'
      }
    ],
    preferentialFlag: false,
    nearestShowtimeCount: 0,
    nearestCinemaCount: 0,
    nearestDay: 0,
    tCn: '潜艇总动员：海底两万里',
    tEn: 'Happy Little Submarine 20000 Leagues under the Sea',
    dN: '申宇',
    aN1: '范楚绒',
    aN2: '洪海天',
    isHasTrailer: false,
    cC: 0,
    sC: 3,
    isNew: false,
    isHot: false,
    isTicket: true,
    is3D: true,
    isIMAX: false,
    isIMAX3D: false,
    isDMAX: false,
    isPromotion: false
  },
  {
    id: 270637,
    movieId: 270637,
    t: '三湾改编',
    year: '2021',
    r: 0,
    rc: 3,
    img: 'http://img5.mtime.cn/mt/2021/07/12/095944.25512749_1280X720X2.jpg',
    m: '',
    actors: '侯京健 / 郭家豪 / 单仕杰 / 廉双岳',
    p: [
      '战争',
      '历史'
    ],
    rd: '20210719',
    d: '110分钟',
    rsC: 0,
    ua: 1,
    def: 0,
    commonSpecial: null,
    wantedCount: 10,
    movieType: '战争 / 历史',
    versions: null,
    preferentialFlag: false,
    nearestShowtimeCount: 0,
    nearestCinemaCount: 0,
    nearestDay: 0,
    tCn: '三湾改编',
    tEn: 'Sanwan Reorganization',
    dN: '杨虎',
    aN1: null,
    aN2: null,
    isHasTrailer: false,
    cC: 0,
    sC: 3,
    isNew: false,
    isHot: false,
    isTicket: true,
    is3D: false,
    isIMAX: false,
    isIMAX3D: false,
    isDMAX: false,
    isPromotion: false
  },
  {
    id: 36998,
    movieId: 36998,
    t: '金沙江畔',
    year: '1963',
    r: -1,
    rc: 17,
    img: 'http://img31.mtime.cn/mt/2014/02/23/030343.91154213_1280X720X2.jpg',
    m: '',
    actors: '冯喆 / 穆宏 / 张伐 / 曹雷',
    p: [
      '剧情',
      '战争'
    ],
    rd: null,
    d: '',
    rsC: 0,
    ua: 1,
    def: 0,
    commonSpecial: null,
    wantedCount: 3,
    movieType: '剧情 / 战争',
    versions: null,
    preferentialFlag: false,
    nearestShowtimeCount: 0,
    nearestCinemaCount: 0,
    nearestDay: 0,
    tCn: '金沙江畔',
    tEn: 'Jinsha jiang pan',
    dN: '傅超武',
    aN1: '冯喆',
    aN2: '穆宏',
    isHasTrailer: false,
    cC: 0,
    sC: 2,
    isNew: false,
    isHot: false,
    isTicket: true,
    is3D: false,
    isIMAX: false,
    isIMAX3D: false,
    isDMAX: false,
    isPromotion: false
  },
  {
    id: 270142,
    movieId: 270142,
    t: '青春之骏',
    year: '2021',
    r: 8,
    rc: 2,
    img: 'http://img5.mtime.cn/mt/2021/03/29/112302.22833044_1280X720X2.jpg',
    m: '',
    actors: null,
    p: null,
    rd: '20210420',
    d: null,
    rsC: 0,
    ua: 1,
    def: 0,
    commonSpecial: null,
    wantedCount: 7,
    movieType: null,
    versions: null,
    preferentialFlag: false,
    nearestShowtimeCount: 0,
    nearestCinemaCount: 0,
    nearestDay: 0,
    tCn: '青春之骏',
    tEn: '',
    dN: null,
    aN1: null,
    aN2: null,
    isHasTrailer: false,
    cC: 0,
    sC: 2,
    isNew: false,
    isHot: false,
    isTicket: true,
    is3D: false,
    isIMAX: false,
    isIMAX3D: false,
    isDMAX: false,
    isPromotion: false
  },
  {
    id: 260717,
    movieId: 260717,
    t: '二哥来了怎么办',
    year: '2021',
    r: 0,
    rc: 48,
    img: 'http://img5.mtime.cn/mt/2021/06/27/100800.44797980_1280X720X2.jpg',
    m: '',
    actors: '胡先煦 / 邓恩熙 / 郑伟 / 代乐乐',
    p: [
      '喜剧',
      '青春',
      '剧情'
    ],
    rd: '20210716',
    d: '',
    rsC: 0,
    ua: 1,
    def: 0,
    commonSpecial: null,
    wantedCount: 76,
    movieType: '喜剧 / 青春 / 剧情',
    versions: [
      {
        versionId: 1,
        version: '2D'
      }
    ],
    preferentialFlag: false,
    nearestShowtimeCount: 0,
    nearestCinemaCount: 0,
    nearestDay: 0,
    tCn: '二哥来了怎么办',
    tEn: 'Hi Brother',
    dN: '郑芬芬',
    aN1: '胡先煦',
    aN2: '邓恩熙',
    isHasTrailer: false,
    cC: 0,
    sC: 2,
    isNew: false,
    isHot: false,
    isTicket: true,
    is3D: false,
    isIMAX: false,
    isIMAX3D: false,
    isDMAX: false,
    isPromotion: false
  },
  {
    id: 270585,
    movieId: 270585,
    t: '寻访马克思',
    year: '2013',
    r: 0,
    rc: 1,
    img: 'http://img5.mtime.cn/mt/2021/07/02/093925.90648823_1280X720X2.jpg',
    m: '',
    actors: '郝蕴',
    p: [
      '纪录片'
    ],
    rd: null,
    d: '99',
    rsC: 0,
    ua: 1,
    def: 0,
    commonSpecial: null,
    wantedCount: 4,
    movieType: '纪录片',
    versions: [
      {
        versionId: 1,
        version: '2D'
      }
    ],
    preferentialFlag: false,
    nearestShowtimeCount: 0,
    nearestCinemaCount: 0,
    nearestDay: 0,
    tCn: '寻访马克思',
    tEn: 'Unveiling Karl Marx',
    dN: '郝蕴',
    aN1: null,
    aN2: null,
    isHasTrailer: false,
    cC: 0,
    sC: 2,
    isNew: false,
    isHot: false,
    isTicket: true,
    is3D: false,
    isIMAX: false,
    isIMAX3D: false,
    isDMAX: false,
    isPromotion: false
  },
  {
    id: 270477,
    movieId: 270477,
    t: '天工苏作',
    year: '2021',
    r: 0,
    rc: 4,
    img: 'http://img5.mtime.cn/mt/2021/06/12/125200.59251301_1280X720X2.jpg',
    m: '',
    actors: '孙增田',
    p: [
      '纪录片'
    ],
    rd: '20210710',
    d: null,
    rsC: 0,
    ua: 1,
    def: 0,
    commonSpecial: null,
    wantedCount: 19,
    movieType: '纪录片',
    versions: null,
    preferentialFlag: false,
    nearestShowtimeCount: 0,
    nearestCinemaCount: 0,
    nearestDay: 0,
    tCn: '天工苏作',
    tEn: '',
    dN: '孙增田',
    aN1: null,
    aN2: null,
    isHasTrailer: false,
    cC: 0,
    sC: 1,
    isNew: false,
    isHot: false,
    isTicket: true,
    is3D: false,
    isIMAX: false,
    isIMAX3D: false,
    isDMAX: false,
    isPromotion: false
  },
  {
    id: 270252,
    movieId: 270252,
    t: '九零后',
    year: '2021',
    r: 0,
    rc: 24,
    img: 'http://img5.mtime.cn/mt/2021/04/24/091859.51371579_1280X720X2.jpg',
    m: '',
    actors: '徐蓓',
    p: [
      '纪录片'
    ],
    rd: '20210529',
    d: '110',
    rsC: 0,
    ua: 1,
    def: 0,
    commonSpecial: null,
    wantedCount: 84,
    movieType: '纪录片',
    versions: [
      {
        versionId: 1,
        version: '2D'
      }
    ],
    preferentialFlag: false,
    nearestShowtimeCount: 0,
    nearestCinemaCount: 0,
    nearestDay: 0,
    tCn: '九零后',
    tEn: 'One Day When We Were Young',
    dN: '徐蓓',
    aN1: null,
    aN2: null,
    isHasTrailer: false,
    cC: 0,
    sC: 1,
    isNew: false,
    isHot: false,
    isTicket: true,
    is3D: false,
    isIMAX: false,
    isIMAX3D: false,
    isDMAX: false,
    isPromotion: false
  },
  {
    id: 270508,
    movieId: 270508,
    t: '大城大楼',
    year: '2021',
    r: 0,
    rc: 0,
    img: 'http://img5.mtime.cn/mt/2021/07/09/153349.34393222_1280X720X2.jpg',
    m: '',
    actors: '陈奕龙 / 李媛 / 佟瑞欣 / 谢鸣晓',
    p: [
      '剧情',
      '青春'
    ],
    rd: '20210723',
    d: null,
    rsC: 0,
    ua: 1,
    def: 0,
    commonSpecial: null,
    wantedCount: 2,
    movieType: '剧情 / 青春',
    versions: null,
    preferentialFlag: false,
    nearestShowtimeCount: 0,
    nearestCinemaCount: 0,
    nearestDay: 0,
    tCn: '大城大楼',
    tEn: '',
    dN: '谢鸣晓',
    aN1: null,
    aN2: null,
    isHasTrailer: false,
    cC: 0,
    sC: 1,
    isNew: false,
    isHot: false,
    isTicket: true,
    is3D: false,
    isIMAX: false,
    isIMAX3D: false,
    isDMAX: false,
    isPromotion: false
  },
  {
    id: 223912,
    movieId: 223912,
    t: '白雪公主之神秘爸爸',
    year: '2015',
    r: 4.4,
    rc: 114,
    img: 'http://img31.mtime.cn/mt/2015/07/23/145902.47046804_1280X720X2.jpg',
    m: '',
    actors: '阎萌萌 / 曹旭鹏 / 高明钰 / 赵奔',
    p: [
      '动画',
      '家庭',
      '冒险'
    ],
    rd: '20150814',
    d: '77 分钟',
    rsC: 0,
    ua: 1,
    def: 0,
    commonSpecial: '白雪公主也开始找爹了',
    wantedCount: 325,
    movieType: '动画 / 家庭 / 冒险',
    versions: [
      {
        versionId: 1,
        version: '2D'
      },
      {
        versionId: 2,
        version: '3D'
      }
    ],
    preferentialFlag: false,
    nearestShowtimeCount: 0,
    nearestCinemaCount: 0,
    nearestDay: 0,
    tCn: '白雪公主之神秘爸爸',
    tEn: 'Snow White: The Mysterious Father',
    dN: '赵奔',
    aN1: '阎萌萌',
    aN2: '曹旭鹏',
    isHasTrailer: false,
    cC: 0,
    sC: 1,
    isNew: false,
    isHot: false,
    isTicket: true,
    is3D: true,
    isIMAX: false,
    isIMAX3D: false,
    isDMAX: false,
    isPromotion: false
  },
  {
    id: 36693,
    movieId: 36693,
    t: '党的女儿',
    year: '1958',
    r: 6.5,
    rc: 54,
    img: 'http://img31.mtime.cn/mt/2016/07/05/141830.58557961_1280X720X2.jpg',
    m: '',
    actors: '田华 / 陈戈 / 李林 / 杜凤侠',
    p: [
      '战争',
      '历史'
    ],
    rd: '19580303',
    d: '',
    rsC: 0,
    ua: 1,
    def: 0,
    commonSpecial: null,
    wantedCount: 4,
    movieType: '战争 / 历史',
    versions: null,
    preferentialFlag: false,
    nearestShowtimeCount: 0,
    nearestCinemaCount: 0,
    nearestDay: 0,
    tCn: '党的女儿',
    tEn: 'Daughter of the Party',
    dN: '林农',
    aN1: '田华',
    aN2: '陈戈',
    isHasTrailer: false,
    cC: 0,
    sC: 1,
    isNew: false,
    isHot: false,
    isTicket: true,
    is3D: false,
    isIMAX: false,
    isIMAX3D: false,
    isDMAX: false,
    isPromotion: false
  },
  {
    id: 266456,
    movieId: 266456,
    t: '匹诺曹',
    year: '2019',
    r: 6.6,
    rc: 85,
    img: 'http://img5.mtime.cn/mt/2021/05/31/154011.79878192_1280X720X2.jpg',
    m: '',
    actors: '费德里科·伊帕迪 / 罗伯托·贝尼尼 / 玛丽恩·瓦斯 / Maurizio Lombardi',
    p: [
      '奇幻'
    ],
    rd: '20210601',
    d: '',
    rsC: 0,
    ua: 1,
    def: 0,
    commonSpecial: null,
    wantedCount: 194,
    movieType: '奇幻',
    versions: null,
    preferentialFlag: false,
    nearestShowtimeCount: 0,
    nearestCinemaCount: 0,
    nearestDay: 0,
    tCn: '匹诺曹',
    tEn: 'Pinocchio',
    dN: '马提欧·加洛尼',
    aN1: '费德里科·伊帕迪',
    aN2: '罗伯托·贝尼尼',
    isHasTrailer: false,
    cC: 0,
    sC: 1,
    isNew: false,
    isHot: false,
    isTicket: true,
    is3D: false,
    isIMAX: false,
    isIMAX3D: false,
    isDMAX: false,
    isPromotion: false
  },
  {
    id: 42206,
    movieId: 42206,
    t: '农奴',
    year: '1963',
    r: 7.5,
    rc: 29,
    img: 'http://img31.mtime.cn/mt/2014/02/23/033331.84642436_1280X720X2.jpg',
    m: '',
    actors: '旺堆 / 强巴 / 小旺堆 / 小多吉',
    p: [
      '剧情'
    ],
    rd: null,
    d: '90分钟',
    rsC: 0,
    ua: 1,
    def: 0,
    commonSpecial: null,
    wantedCount: 9,
    movieType: '剧情',
    versions: null,
    preferentialFlag: false,
    nearestShowtimeCount: 0,
    nearestCinemaCount: 0,
    nearestDay: 0,
    tCn: '农奴',
    tEn: 'Nong Nu',
    dN: '李俊',
    aN1: '旺堆',
    aN2: '强巴',
    isHasTrailer: false,
    cC: 0,
    sC: 1,
    isNew: false,
    isHot: false,
    isTicket: true,
    is3D: false,
    isIMAX: false,
    isIMAX3D: false,
    isDMAX: false,
    isPromotion: false
  },
  {
    id: 36958,
    movieId: 36958,
    t: '鸡毛信',
    year: '1954',
    r: 7.3,
    rc: 168,
    img: 'http://img31.mtime.cn/mt/2014/02/23/030336.53639002_1280X720X2.jpg',
    m: '',
    actors: '舒适 / 蔡元元 / 李保罗 / 曹铎',
    p: [
      '战争'
    ],
    rd: null,
    d: '70分钟',
    rsC: 0,
    ua: 1,
    def: 0,
    commonSpecial: null,
    wantedCount: 8,
    movieType: '战争',
    versions: null,
    preferentialFlag: false,
    nearestShowtimeCount: 0,
    nearestCinemaCount: 0,
    nearestDay: 0,
    tCn: '鸡毛信',
    tEn: 'The Letter With Feathers',
    dN: '石挥',
    aN1: '舒适',
    aN2: '蔡元元',
    isHasTrailer: false,
    cC: 0,
    sC: 1,
    isNew: false,
    isHot: false,
    isTicket: true,
    is3D: false,
    isIMAX: false,
    isIMAX3D: false,
    isDMAX: false,
    isPromotion: false
  },
  {
    id: 270059,
    movieId: 270059,
    t: '了不起的老爸',
    year: '2021',
    r: 7,
    rc: 100,
    img: 'http://img5.mtime.cn/mt/2021/06/02/143209.21788331_1280X720X2.jpg',
    m: '',
    actors: '张宥浩 / 王砚辉 / 龚蓓苾 / 鹤男',
    p: [
      '家庭',
      '剧情',
      '喜剧'
    ],
    rd: '20210618',
    d: '104分钟',
    rsC: 0,
    ua: 1,
    def: 0,
    commonSpecial: null,
    wantedCount: 131,
    movieType: '家庭 / 剧情 / 喜剧',
    versions: null,
    preferentialFlag: false,
    nearestShowtimeCount: 0,
    nearestCinemaCount: 0,
    nearestDay: 0,
    tCn: '了不起的老爸',
    tEn: 'On Your Mark',
    dN: '周青元',
    aN1: '张宥浩',
    aN2: '王砚辉',
    isHasTrailer: false,
    cC: 0,
    sC: 1,
    isNew: false,
    isHot: false,
    isTicket: true,
    is3D: false,
    isIMAX: false,
    isIMAX3D: false,
    isDMAX: false,
    isPromotion: false
  },
  {
    id: 270587,
    movieId: 270587,
    t: '失恋之城',
    year: '2021',
    r: 0,
    rc: 0,
    img: 'http://img5.mtime.cn/mt/2021/07/02/094710.19181918_1280X720X2.jpg',
    m: '',
    actors: '王雷方 / 于函冰 / 夏雷 / 苗述',
    p: [
      '爱情',
      '剧情'
    ],
    rd: '20210814',
    d: '91',
    rsC: 0,
    ua: 1,
    def: 0,
    commonSpecial: null,
    wantedCount: 5,
    movieType: '爱情 / 剧情',
    versions: [
      {
        versionId: 1,
        version: '2D'
      }
    ],
    preferentialFlag: false,
    nearestShowtimeCount: 0,
    nearestCinemaCount: 0,
    nearestDay: 0,
    tCn: '失恋之城',
    tEn: '',
    dN: '苗述',
    aN1: null,
    aN2: null,
    isHasTrailer: false,
    cC: 0,
    sC: 1,
    isNew: true,
    isHot: false,
    isTicket: true,
    is3D: false,
    isIMAX: false,
    isIMAX3D: false,
    isDMAX: false,
    isPromotion: false
  }
];
